### PR TITLE
Merge latest upstream

### PR DESCRIPTION
**Pull request by SparkingSpork**
Merge latest from upstream.

No conflict resolution performed.

AB#2395767

## Testing:
- [x] Ran `bitbake packagefeed-ni-core`
- [x] Ran `bitbake packagegroup-ni-desirable`

### CODE REVIEW

**Comment by SparkingSpork** [comment]
## V2:
- Added comment to merge commit that no conflict resolution was performed.

**Review by chaitu236 — COMMENTED** [review]
A merge commit shouldn't have been generated as we didn't put in any NI specific changes. Seems like the commits in https://github.com/ni/bitbake/pull/13 got different hashes from upstream - not sure what happened. @amstewart 

We'd probably want to revert those two and re-run the merge script on this repo

**Comment by amstewart** [comment]
@chaitu236 I have no idea why dturner's commits from #13 have different hashes from what was eventually merged. Nor why it seems to have only happened on the bitbake branch. I should really make some scripting to make the pulling process more reliable.

Either way, the fix will be to pull in the merge commit that this PR has generated.

**Review by amstewart — APPROVED** [review]

**Comment by chaitu236** [comment]
> Either way, the fix will be to pull in the merge commit that this PR has generated.

Wouldn't creating a merge commit now cause future merges to also generate merge commits?

**Comment by SparkingSpork** [comment]
> Wouldn't creating a merge commit now cause future merges to also generate merge commits?

Not sure I follow this. Wouldn't the merge commit be a one time thing that resolves the merge conflicts? So future merges wouldn't have the conflicts?

**Comment by amstewart** [comment]
Once we have stepped off of the upstream sequence of hashes, even with an empty merge commit, all subsequent merges will generate a merge commit until we rebase. But even if we revert the two previous commits that changed hashes, we'll still be out of stream.

We would have to reset the head back to where the fork happened and redo the merge, then do a force-push. And while we could do that, I don't think it's worth the effort. All these commits should collapse away in the rebase regardless.

**Comment by chaitu236** [comment]
> Wouldn't the merge commit be a one time thing that resolves the merge conflicts? So future merges wouldn't have the conflicts?

^ what Alex said.

> But even if we revert the two previous commits that changed hashes, we'll still be out of stream.

Ah yes, I forgot that even with these reverted our HEAD would be different so we'll still have empty merge commits.

> We would have to reset the head back to where the fork happened and redo the merge, then do a force-push. And while we could do that, I don't think it's worth the effort.

Yeah lets not do that. I'm ok with this change then.

**Review by chaitu236 — APPROVED** [review]

**Pull request merged**
